// <auto-generated />
namespace Gestion_Etudiant.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class first_de_la_migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(first_de_la_migration));
        
        string IMigrationMetadata.Id
        {
            get { return "202502262053365_first_de_la_migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
